# ===============================
# APPLICATION
# ===============================
spring.application.name=api-gateway
server.port=8080

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# JWT
# ===============================
jwt.secret=617b7c292a0698a897e6ff73324285be2ca049857c8802e26a4cce2214d899c4


# ===============================
# USER SERVICE ROUTES
# ===============================

spring.cloud.gateway.routes[0].id=user-service-users
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=user-service-admin
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/admin/**

spring.cloud.gateway.routes[2].id=user-service-buyer
spring.cloud.gateway.routes[2].uri=lb://user-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/buyer/**

spring.cloud.gateway.routes[3].id=user-service-seller
spring.cloud.gateway.routes[3].uri=lb://user-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/seller/**


# ===============================
# AUCTION SERVICE ROUTES
# ===============================

spring.cloud.gateway.routes[4].id=auction-service
spring.cloud.gateway.routes[4].uri=lb://auction-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auctions/**,/api/seller/auctions/**,/api/admin/auctions/**


# ===============================
# BID SERVICE ROUTES  ? NEW
# ===============================

spring.cloud.gateway.routes[5].id=bid-service
spring.cloud.gateway.routes[5].uri=lb://bid-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/bids/**,/api/buyer/bids/**


# ===============================
# SWAGGER ROUTES
# ===============================

spring.cloud.gateway.routes[6].id=user-service-swagger
spring.cloud.gateway.routes[6].uri=lb://user-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/user-service/v3/api-docs
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/user-service/v3/api-docs,/v3/api-docs

spring.cloud.gateway.routes[7].id=auction-service-swagger
spring.cloud.gateway.routes[7].uri=lb://auction-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/auction-service/v3/api-docs
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/auction-service/v3/api-docs,/v3/api-docs

spring.cloud.gateway.routes[8].id=bid-service-swagger
spring.cloud.gateway.routes[8].uri=lb://bid-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/bid-service/v3/api-docs
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/bid-service/v3/api-docs,/v3/api-docs


# ===============================
# SWAGGER UI
# ===============================

springdoc.swagger-ui.path=/swagger-ui

springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Auction Service
springdoc.swagger-ui.urls[1].url=/auction-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=Bid Service
springdoc.swagger-ui.urls[2].url=/bid-service/v3/api-docs
